# Generated by Django 5.1.7 on 2025-08-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='anomaly',
            field=models.CharField(choices=[('asteroid-field', 'Asteroid Field'), ('gravity-rift', 'Gravity Rift'), ('muatt-supernova', 'Muatt Supernova'), ('Nebula', 'Nebula'), ('supernova', 'Supernova'), ('zelian-asteroid-field', 'Zelian Asteroid Field'), ('myko-cataclysm', 'Myko Cataclysm'), ('asteroid-nebula', 'Asteroid Nebula'), ('asteroid-rift', 'Asteroid Rift'), ('none', 'None')], default='none', max_length=21),
        ),
    ]
