# Generated by Django 5.1.7 on 2026-06-14 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_system_anomaly'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_type', models.CharField(choices=[('rules', 'Rules Chat'), ('strategy', 'Strategic Plan'), ('move', 'Tactical Move'), ('tac_calc', 'Battle Calculator')], max_length=20)),
                ('input_payload_json', models.JSONField(default=dict, help_text='Feature inputs (question / board / fleets). Never the API key.')),
                ('result_payload_json', models.JSONField(blank=True, help_text='The response the frontend renders, once the job completes.', null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timed Out'), ('validation_failed', 'Validation Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('model_provider', models.CharField(blank=True, default='', max_length=30)),
                ('model_name', models.CharField(blank=True, default='', max_length=60)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
