# Generated by Django 5.1.7 on 2026-06-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aijob'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='legendary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='system',
            name='anomaly',
            field=models.CharField(choices=[('asteroid-field', 'Asteroid Field'), ('gravity-rift', 'Gravity Rift'), ('muaat-supernova', 'Muaat Supernova'), ('nebula', 'Nebula'), ('supernova', 'Supernova'), ('zelian-asteroid-field', 'Zelian Asteroid Field'), ('myko-cataclysm', 'Myko Cataclysm'), ('asteroid-nebula', 'Asteroid Nebula'), ('asteroid-rift', 'Asteroid Rift'), ('none', 'None')], default='none', max_length=21),
        ),
    ]
