DEFAULT_SYSTEMS = [
    {"tile_id": 1, "name": "Sol System", "planets": ["Jord"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 2, "name": "Mentak System", "planets": ["Moll Primus"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 3, "name": "Yin System", "planets": ["Darien"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4, "name": "Muaat System", "planets": ["Muaat"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 5, "name": "Arborec System", "planets": ["Nestphar"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 6, "name": "L1z1x System", "planets": ["[0.0.0]"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 7, "name": "Winnu System", "planets": ["Winnu"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 8, "name": "Nekro System", "planets": ["Mordai II"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 9, "name": "Naalu System", "planets": ["Maaluuk", "Druaa"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 10, "name": "Letnev System", "planets": ["Arc Prime", "Wren Terra"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 11, "name": "Saar System", "planets": ["Lisis II", "Ragh"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 12, "name": "Jol-Nar System", "planets": ["Jol", "Nar"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 13, "name": "Sardakk System", "planets": ["Tren'lak", "Quinarra"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 14, "name": "Xxcha System", "planets": ["Archon Ren", "Archon Tau"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 15, "name": "Yssaril System", "planets": ["Retillion", "Shalloq"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 16, "name": "Hacan System", "planets": ["Arretze", "Hercant", "Kamdorn"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 17, "name": "Creuss Wormhole System", "planets": [], "anomaly": "none", "wormhole": "delta"},
    {"tile_id": 18, "name": "Mecatol Rex System", "planets": ["Mecatol Rex"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 19, "name": "Wellon System", "planets": ["Wellon"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 20, "name": "Vefut System", "planets": ["Vefut II"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 21, "name": "Thibah System", "planets": ["Thibah"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 22, "name": "Tar'mann System", "planets": ["Tar'mann"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 23, "name": "Saudor System", "planets": ["Saudor"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 24, "name": "Mehar Xull System", "planets": ["Mehar Xull"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 25, "name": "Quann System", "planets": ["Quann"], "anomaly": "none", "wormhole": "beta"},
    {"tile_id": 26, "name": "Lodor System", "planets": ["Lodor"], "anomaly": "none", "wormhole": "alpha"},
    {"tile_id": 27, "name": "New Albion-Starpoint System", "planets": ["New Albion", "Starpoint"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 28, "name": "Tequ'ran-Torkan System", "planets": ["Tequ'ran", "Torkan"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 29, "name": "Qucen'n-Rarron System", "planets": ["Qucen'n", "Rarron"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 30, "name": "Mellon-Zohbat System", "planets": ["Mellon", "Zohbat"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 31, "name": "Lazar-Sakulag System", "planets": ["Lazar", "Sakulag"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 32, "name": "Dal Bootha-Xxehan System", "planets": ["Dal Bootha", "Xxehan"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 33, "name": "Corneeq-Resulon System", "planets": ["Corneeq", "Resulon"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 34, "name": "Centauri-Gral System", "planets": ["Centauri", "Gral"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 35, "name": "Bereg-Lirta System", "planets": ["Bereg", "Lirta IV"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 36, "name": "Arnor-Lor System", "planets": ["Arnor", "Lor"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 37, "name": "Arinam-Meer System", "planets": ["Arinam", "Meer"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 38, "name": "Abyz-Fria System", "planets": ["Abyz", "Fria"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 39, "name": "Alpha Wormhole System", "planets": [], "anomaly": "none", "wormhole": "alpha"},
    {"tile_id": 40, "name": "Beta Wormhole System", "planets": [], "anomaly": "none", "wormhole": "beta"},
    {"tile_id": 41, "name": "Gravity Rift 1 System", "planets": [], "anomaly": "gravity-rift", "wormhole": "none"},
    {"tile_id": 42, "name": "Nebula System", "planets": [], "anomaly": "nebula", "wormhole": "none"},
    {"tile_id": 43, "name": "Supernova 1 System", "planets": [], "anomaly": "supernova", "wormhole": "none"},
    {"tile_id": 44, "name": "Asteroid Field 1 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "none"},
    {"tile_id": 45, "name": "Asteroid Field 2 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "none"},
    {"tile_id": 46, "name": "Empty 1", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 47, "name": "Empty 2", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 48, "name": "Empty 3", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 49, "name": "Empty 4", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 50, "name": "Empty 5", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 51, "name": "Creuss Home System", "planets": ["Creuss"], "anomaly": "none", "wormhole": "delta"},
    {"tile_id": 52, "name": "Mahact System", "planets": ["Ixth"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 53, "name": "Nomad System", "planets": ["Arcturus"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 54, "name": "Vuil'raith System", "planets": ["Acheron"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 55, "name": "Titans System", "planets": ["Elysium"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 56, "name": "Empyrean System", "planets": ["The Dark"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 57, "name": "Naaz-Rokha System", "planets": ["Naazir", "Rokha"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 58, "name": "Argent System", "planets": ["Valk", "Avar", "Ylir"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 59, "name": "Archon Vail System", "planets": ["Archon Vail"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 60, "name": "Perimeter System", "planets": ["Perimeter"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 61, "name": "Ang System", "planets": ["Ang"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 62, "name": "Sem-Lore System", "planets": ["Sem-Lore"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 63, "name": "Vorhal System", "planets": ["Vorhal"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 64, "name": "Atlas System", "planets": ["Atlas"], "anomaly": "none", "wormhole": "beta"},
    {"tile_id": 65, "name": "Primor System", "planets": ["Primor"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 66, "name": "Hope's End System", "planets": ["Hope's End"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 67, "name": "Cormund System", "planets": ["Cormund"], "anomaly": "gravity-rift", "wormhole": "none"},
    {"tile_id": 68, "name": "Everra System", "planets": ["Everra"], "anomaly": "nebula", "wormhole": "none"},
    {"tile_id": 69, "name": "Accoen-Jeol System", "planets": ["Accoen", "Jeol Ir"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 70, "name": "Kraag-Siig System", "planets": ["Kraag", "Siig"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 71, "name": "Ba-Alio System", "planets": ["Ba'Kal", "Alio Prima"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 72, "name": "Lisis-Velnor System", "planets": ["Lisis", "Velnor"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 73, "name": "Cealdri-Xanhact System", "planets": ["Cealdri", "Xanhact"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 74, "name": "Vega System", "planets": ["Vega Major", "Vega Minor"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 75, "name": "Loki-Abaddon-Ashtroth System", "planets": ["Loki", "Abaddon", "Ashtroth"],
     "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 76, "name": "Rigel System", "planets": ["Rigel I", "Rigel II", "Rigel III"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 77, "name": "Empty 6", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 78, "name": "Empty 7", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 79, "name": "Asteroid Field 3 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "alpha"},
    {"tile_id": 80, "name": "Supernova 2 System", "planets": [], "anomaly": "supernova", "wormhole": "none"},
    {"tile_id": 81, "name": "Muaat Supernova System", "planets": [], "anomaly": "muaat-supernova", "wormhole": "none"},
    {"tile_id": 82, "name": "Mallice System", "planets": ["Mallice"], "anomaly": "none", "wormhole": "all"}
]
