DEFAULT_FACTIONS = [
    {"name": "arborec", "home_system": "Arborec System"},
    {"name": "letnev", "home_system": "Letnev System"},
    {"name": "saar", "home_system": "Saar System"},
    {"name": "muatt", "home_system": "Muaat System"},
    {"name": "hacan", "home_system": "Hacan System"},
    {"name": "sol", "home_system": "Sol System"},
    {"name": "creuss", "home_system": "Creuss Wormhole System"},
    {"name": "l1z1x", "home_system": "L1z1x System"},
    {"name": "mentak", "home_system": "Mentak System"},
    {"name": "naalu", "home_system": "Naalu System"},
    {"name": "sardakk", "home_system": "Sardakk System"},
    {"name": "jolnar", "home_system": "Jol-Nar System"},
    {"name": "winnu", "home_system": "Winnu System"},
    {"name": "xxcha", "home_system": "Xxcha System"},
    {"name": "yin", "home_system": "Yin System"},
    {"name": "yssaril", "home_system": "Yssaril System"},
    {"name": "nekro", "home_system": "Nekro System"},
    {"name": "argent", "home_system": "Argent System"},
    {"name": "empyrean", "home_system": "Empyrean System"},
    {"name": "mahact", "home_system": "Mahact System"},
    {"name": "naazrokha", "home_system": "Naaz-Rokha System"},
    {"name": "nomad", "home_system": "Nomad System"},
    {"name": "ul", "home_system": "Titans System"},
    {"name": "vuilraith", "home_system": "Vuil'raith System"}
]
