DEFAULT_PLANETS = [
    # Home Planets
    {"name": "Jord", "resources": 4, "influence": 2, "trait": "none", "tech_specialty": "none"},
    {"name": "Moll Primus", "resources": 4, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "Darien", "resources": 4, "influence": 4, "trait": "none", "tech_specialty": "none"},
    {"name": "Muaat", "resources": 4, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "Nestphar", "resources": 3, "influence": 2, "trait": "none", "tech_specialty": "none"},
    {"name": "[0.0.0]", "resources": 5, "influence": 0, "trait": "none", "tech_specialty": "none"},
    {"name": "Winnu", "resources": 3, "influence": 4, "trait": "none", "tech_specialty": "none"},
    {"name": "Mordai II", "resources": 4, "influence": 0, "trait": "none", "tech_specialty": "none"},
    {"name": "Maaluuk", "resources": 0, "influence": 2, "trait": "none", "tech_specialty": "none"},
    {"name": "Druaa", "resources": 3, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "Arc Prime", "resources": 4, "influence": 0, "trait": "none", "tech_specialty": "none"},
    {"name": "Wren Terra", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "Lisis II", "resources": 1, "influence": 0, "trait": "none", "tech_specialty": "none"},
    {"name": "Ragh", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "Jol", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
    {"name": "Nar", "resources": 2, "influence": 3, "trait": "none", "tech_specialty": "none"},
    {"name": "Tren'lak", "resources": 1, "influence": 0, "trait": "none", "tech_specialty": "none"},
    {"name": "Quinarra", "resources": 3, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "Archon Ren", "resources": 2, "influence": 3, "trait": "none", "tech_specialty": "none"},
    {"name": "Archon Tau", "resources": 1, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "Retillion", "resources": 2, "influence": 3, "trait": "none", "tech_specialty": "none"},
    {"name": "Shalloq", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
    {"name": "Arretze", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
    {"name": "Hercant", "resources": 1, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "Kamdorn", "resources": 0, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "Creuss", "resources": 4, "influence": 2, "trait": "none", "tech_specialty": "none"},
    {"name": "Ixth", "resources": 3, "influence": 5, "trait": "none", "tech_specialty": "none"},
    {"name": "Arcturus", "resources": 4, "influence": 4, "trait": "none", "tech_specialty": "none"},
    {"name": "Acheron", "resources": 4, "influence": 0, "trait": "none", "tech_specialty": "none"},
    {"name": "Elysium", "resources": 4, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "The Dark", "resources": 3, "influence": 4, "trait": "none", "tech_specialty": "none"},
    {"name": "Naazir", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "Rokha", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
    {"name": "Valk", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
    {"name": "Avar", "resources": 1, "influence": 1, "trait": "none", "tech_specialty": "none"},
    {"name": "Ylir", "resources": 0, "influence": 2, "trait": "none", "tech_specialty": "none"},
    # Non-Home Planets
    {"name": "Mecatol Rex", "resources": 1, "influence": 6, "trait": "none", "tech_specialty": "none"},
    {"name": "Wellon", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "yellow"},
    {"name": "Vefut II", "resources": 2, "influence": 2, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Thibah", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "blue"},
    {"name": "Tar'mann", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "green"},
    {"name": "Saudor", "resources": 2, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
    {"name": "Mehar Xull", "resources": 1, "influence": 3, "trait": "hazardous", "tech_specialty": "red"},
    {"name": "Quann", "resources": 2, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Lodor", "resources": 3, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
    {"name": "New Albion", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "green"},
    {"name": "Starpoint", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Tequ'ran", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Torkan", "resources": 0, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Qucen'n", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
    {"name": "Rarron", "resources": 0, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Mellon", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Zohbat", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Lazar", "resources": 1, "influence": 0, "trait": "industrial", "tech_specialty": "yellow"},
    {"name": "Sakulag", "resources": 2, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Dal Bootha", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Xxehan", "resources": 1, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Corneeq", "resources": 1, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Resulon", "resources": 2, "influence": 0, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Centauri", "resources": 1, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Gral", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "blue"},
    {"name": "Bereg", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Lirta IV", "resources": 2, "influence": 3, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Arnor", "resources": 2, "influence": 1, "trait": "industrial", "tech_specialty": "none"},
    {"name": "Lor", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
    {"name": "Arinam", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
    {"name": "Meer", "resources": 0, "influence": 4, "trait": "hazardous", "tech_specialty": "red"},
    {"name": "Abyz", "resources": 3, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Fria", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Archon Vail", "resources": 1, "influence": 3, "trait": "hazardous", "tech_specialty": "blue"},
    {"name": "Perimeter", "resources": 2, "influence": 1, "trait": "industrial", "tech_specialty": "none"},
    {"name": "Ang", "resources": 2, "influence": 0, "trait": "industrial", "tech_specialty": "red"},
    {"name": "Sem-Lore", "resources": 3, "influence": 2, "trait": "cultural", "tech_specialty": "yellow"},
    {"name": "Vorhal", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "green"},
    {"name": "Atlas", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Cormund", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Everra", "resources": 3, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Accoen", "resources": 2, "influence": 3, "trait": "industrial", "tech_specialty": "none"},
    {"name": "Jeol Ir", "resources": 2, "influence": 3, "trait": "industrial", "tech_specialty": "none"},
    {"name": "Kraag", "resources": 2, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Siig", "resources": 0, "influence": 2, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Ba'Kal", "resources": 3, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
    {"name": "Alio Prima", "resources": 1, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Lisis", "resources": 2, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
    {"name": "Velnor", "resources": 2, "influence": 1, "trait": "industrial", "tech_specialty": "red"},
    {"name": "Cealdri", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "yellow"},
    {"name": "Xanhact", "resources": 0, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Vega Major", "resources": 2, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Vega Minor", "resources": 1, "influence": 2, "trait": "cultural", "tech_specialty": "blue"},
    {"name": "Loki", "resources": 1, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Abaddon", "resources": 1, "influence": 0, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Ashtroth", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Rigel I", "resources": 0, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Rigel II", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
    {"name": "Rigel III", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "green"},
    # Legendaries
    {"name": "Primor", "resources": 2, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
    {"name": "Hope's End", "resources": 3, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
    {"name": "Mallice", "resources": 0, "influence": 3, "trait": "cultural", "tech_specialty": "none"}
]
