# Generated by Django 5.1.7 on 2025-04-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_player_faction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groundunit',
            name='planet',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='position',
        ),
        migrations.AlterField(
            model_name='groundunit',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='structure',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('ships', models.ManyToManyField(related_name='fleets', to='core.ship')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='fleet',
            field=models.ManyToManyField(related_name='systems', to='core.fleet'),
        ),
    ]
