# Generated by Django 5.1.7 on 2025-04-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_groundunit_planet_remove_ship_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='fleet',
        ),
        migrations.AddField(
            model_name='system',
            name='fleet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fleet'),
        ),
    ]
