DEFAULT_SYSTEMS = [
    {"tile_id": 1, "name": "Sol System", "planets": ["Jord"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 2, "name": "Mentak System", "planets": ["Moll Primus"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 3, "name": "Yin System", "planets": ["Darien"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4, "name": "Muaat System", "planets": ["Muaat"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 5, "name": "Arborec System", "planets": ["Nestphar"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 6, "name": "L1z1x System", "planets": ["[0.0.0]"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 7, "name": "Winnu System", "planets": ["Winnu"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 8, "name": "Nekro System", "planets": ["Mordai II"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 9, "name": "Naalu System", "planets": ["Maaluuk", "Druaa"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 10, "name": "Letnev System", "planets": ["Arc Prime", "Wren Terra"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 11, "name": "Saar System", "planets": ["Lisis II", "Ragh"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 12, "name": "Jol-Nar System", "planets": ["Jol", "Nar"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 13, "name": "Sardakk System", "planets": ["Tren'lak", "Quinarra"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 14, "name": "Xxcha System", "planets": ["Archon Ren", "Archon Tau"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 15, "name": "Yssaril System", "planets": ["Retillion", "Shalloq"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 16, "name": "Hacan System", "planets": ["Arretze", "Hercant", "Kamdorn"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 17, "name": "Creuss Wormhole System", "planets": [], "anomaly": "none", "wormhole": "delta"},
    {"tile_id": 18, "name": "Mecatol Rex System", "planets": ["Mecatol Rex"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 19, "name": "Wellon System", "planets": ["Wellon"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 20, "name": "Vefut System", "planets": ["Vefut II"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 21, "name": "Thibah System", "planets": ["Thibah"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 22, "name": "Tar'mann System", "planets": ["Tar'mann"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 23, "name": "Saudor System", "planets": ["Saudor"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 24, "name": "Mehar Xull System", "planets": ["Mehar Xull"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 25, "name": "Quann System", "planets": ["Quann"], "anomaly": "none", "wormhole": "beta"},
    {"tile_id": 26, "name": "Lodor System", "planets": ["Lodor"], "anomaly": "none", "wormhole": "alpha"},
    {"tile_id": 27, "name": "New Albion-Starpoint System", "planets": ["New Albion", "Starpoint"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 28, "name": "Tequ'ran-Torkan System", "planets": ["Tequ'ran", "Torkan"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 29, "name": "Qucen'n-Rarron System", "planets": ["Qucen'n", "Rarron"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 30, "name": "Mellon-Zohbat System", "planets": ["Mellon", "Zohbat"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 31, "name": "Lazar-Sakulag System", "planets": ["Lazar", "Sakulag"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 32, "name": "Dal Bootha-Xxehan System", "planets": ["Dal Bootha", "Xxehan"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 33, "name": "Corneeq-Resulon System", "planets": ["Corneeq", "Resulon"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 34, "name": "Centauri-Gral System", "planets": ["Centauri", "Gral"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 35, "name": "Bereg-Lirta System", "planets": ["Bereg", "Lirta IV"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 36, "name": "Arnor-Lor System", "planets": ["Arnor", "Lor"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 37, "name": "Arinam-Meer System", "planets": ["Arinam", "Meer"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 38, "name": "Abyz-Fria System", "planets": ["Abyz", "Fria"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 39, "name": "Alpha Wormhole System", "planets": [], "anomaly": "none", "wormhole": "alpha"},
    {"tile_id": 40, "name": "Beta Wormhole System", "planets": [], "anomaly": "none", "wormhole": "beta"},
    {"tile_id": 41, "name": "Gravity Rift 1 System", "planets": [], "anomaly": "gravity-rift", "wormhole": "none"},
    {"tile_id": 42, "name": "Nebula System", "planets": [], "anomaly": "nebula", "wormhole": "none"},
    {"tile_id": 43, "name": "Supernova 1 System", "planets": [], "anomaly": "supernova", "wormhole": "none"},
    {"tile_id": 44, "name": "Asteroid Field 1 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "none"},
    {"tile_id": 45, "name": "Asteroid Field 2 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "none"},
    {"tile_id": 46, "name": "Empty 1", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 47, "name": "Empty 2", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 48, "name": "Empty 3", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 49, "name": "Empty 4", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 50, "name": "Empty 5", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 51, "name": "Creuss Home System", "planets": ["Creuss"], "anomaly": "none", "wormhole": "delta"},
    {"tile_id": 52, "name": "Mahact System", "planets": ["Ixth"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 53, "name": "Nomad System", "planets": ["Arcturus"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 54, "name": "Vuil'raith System", "planets": ["Acheron"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 55, "name": "Titans System", "planets": ["Elysium"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 56, "name": "Empyrean System", "planets": ["The Dark"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 57, "name": "Naaz-Rokha System", "planets": ["Naazir", "Rokha"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 58, "name": "Argent System", "planets": ["Valk", "Avar", "Ylir"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 59, "name": "Archon Vail System", "planets": ["Archon Vail"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 60, "name": "Perimeter System", "planets": ["Perimeter"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 61, "name": "Ang System", "planets": ["Ang"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 62, "name": "Sem-Lore System", "planets": ["Sem-Lore"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 63, "name": "Vorhal System", "planets": ["Vorhal"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 64, "name": "Atlas System", "planets": ["Atlas"], "anomaly": "none", "wormhole": "beta"},
    {"tile_id": 65, "name": "Primor System", "planets": ["Primor"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 66, "name": "Hope's End System", "planets": ["Hope's End"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 67, "name": "Cormund System", "planets": ["Cormund"], "anomaly": "gravity-rift", "wormhole": "none"},
    {"tile_id": 68, "name": "Everra System", "planets": ["Everra"], "anomaly": "nebula", "wormhole": "none"},
    {"tile_id": 69, "name": "Accoen-Jeol System", "planets": ["Accoen", "Jeol Ir"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 70, "name": "Kraag-Siig System", "planets": ["Kraag", "Siig"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 71, "name": "Ba-Alio System", "planets": ["Ba'Kal", "Alio Prima"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 72, "name": "Lisis-Velnor System", "planets": ["Lisis", "Velnor"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 73, "name": "Cealdri-Xanhact System", "planets": ["Cealdri", "Xanhact"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 74, "name": "Vega System", "planets": ["Vega Major", "Vega Minor"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 75, "name": "Loki-Abaddon-Ashtroth System", "planets": ["Loki", "Abaddon", "Ashtroth"],
     "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 76, "name": "Rigel System", "planets": ["Rigel I", "Rigel II", "Rigel III"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 77, "name": "Empty 6", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 78, "name": "Empty 7", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 79, "name": "Asteroid Field 3 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "alpha"},
    {"tile_id": 80, "name": "Supernova 2 System", "planets": [], "anomaly": "supernova", "wormhole": "none"},
    {"tile_id": 81, "name": "Muaat Supernova System", "planets": [], "anomaly": "muaat-supernova", "wormhole": "none"},
    {"tile_id": 82, "name": "Mallice System", "planets": ["Mallice"], "anomaly": "none", "wormhole": "all"},
    {"tile_id": 4200, "name": "Veldyr System", "planets": ["Rhune"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4222, "name": "Free System", "planets": ["Idyn, Kroll, Cyrra"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4223, "name": "Li-Zho System", "planets": ["Kyr, Pax, Vess"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4201, "name": "Khrask System", "planets": ["Bohl-Dhur"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4212, "name": "Ghemina System", "planets": ["Drah, Trykk"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4213, "name": "Vaden System", "planets": ["Vadarian, Norvus"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4214, "name": "Mortheus System", "planets": ["Blaheo, Empero"], "anomaly": "nebula", "wormhole": "none"},
    {"tile_id": 4215, "name": "Ilyxum System", "planets": ["Chrion, Demis"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4204, "name": "Axis System", "planets": ["Axis"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4205, "name": "Olradin System", "planets": ["Sanctuary"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4206, "name": "Myko System", "planets": ["Shi-Halaum"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4207, "name": "Tnelis System", "planets": ["Discordia"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4203, "name": "Cymiae System", "planets": ["Cymiae"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4208, "name": "Roh'Dhna System", "planets": ["Prind"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4216, "name": "Zelian System", "planets": ["Zelian, Gen"], "anomaly": "asteroid-field", "wormhole": "none"},
    {"tile_id": 4209, "name": "Vaylerian System", "planets": ["Vaylar"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4217, "name": "Florzen System", "planets": ["Delmor, Kyd"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4210, "name": "Dih-Mohn System", "planets": ["Abyssus"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4218, "name": "Celdauri System", "planets": ["Louk, Auldane"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4211, "name": "Nivyn System", "planets": ["Ellas"], "anomaly": "gravity-rift", "wormhole": "none"},
    {"tile_id": 4219, "name": "Mirveda System", "planets": ["Aldra, Beata"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4220, "name": "Kortali System", "planets": ["Ogdun, Brthkul"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4202, "name": "Kollecc System", "planets": ["Susuros"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4221, "name": "Rhodun System", "planets": ["Poh, Orad"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4224, "name": "Zelian Asteroid Field System", "planets": [], "anomaly": "zelian-asteroid-field",
     "wormhole": "none"},
    {"tile_id": 4225, "name": "Myko Cataclysm System", "planets": [], "anomaly": "myko-cataclysm", "wormhole": "none"},
    {"tile_id": 4230, "name": "Bentor System", "planets": ["Benc, Hau"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4231, "name": "Nokar System", "planets": ["Zarr, Nokk"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4228, "name": "Gledge System", "planets": ["Last Stop"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4232, "name": "Lanefir System", "planets": ["Aysis' Rest, Solitude"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4229, "name": "Kyro System", "planets": ["Avicenna"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4227, "name": "Ghoti System", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4233, "name": "Kolume System", "planets": ["Alesna, Azle"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4234, "name": "Cheiran System", "planets": ["Gghurn Theta, Arche"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4236, "name": "Edyn System", "planets": ["Edyn, Ekko, Okke"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4235, "name": "Kjalengard System", "planets": ["Kjalengard, Hulgade"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 4253, "name": "Silence System", "planets": ["Silence"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4254, "name": "Echo System", "planets": ["Echo"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4255, "name": "Tarrock System", "planets": ["Tarrock"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4256, "name": "Prism System", "planets": ["Prism"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4257, "name": "Troac System", "planets": ["Troac"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4258, "name": "Etir System", "planets": ["Etir V"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4259, "name": "Vioss System", "planets": ["Vioss"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4260, "name": "Fakrenn System", "planets": ["Fakrenn"], "anomaly": "none", "wormhole": "alpha"},
    {"tile_id": 4261, "name": "San-Lodran System", "planets": ["San-Vit, Lodran"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4262, "name": "Dorvok-Derbrae System", "planets": ["Dorvok, Derbrae"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 4263, "name": "Rysaa-Moln System", "planets": ["Rysaa, Moln"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4264, "name": "Salin-Gwiyun System", "planets": ["Salin, Gwiyun"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4265, "name": "Inan-Swog System", "planets": ["Inan, Swog"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4266, "name": "Detic-Lliot System", "planets": ["Detic, Lliot"], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4267, "name": "Qaak-Larred-Nairb System", "planets": ["Qaak, Larred, Nairb"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 4268, "name": "Mandle-Sierpen-Regnem System", "planets": ["Mandle, Sierpen, Regnem"], "anomaly": "none",
     "wormhole": "none"},
    {"tile_id": 4269, "name": "Domna System", "planets": ["Domna"], "anomaly": "nebula", "wormhole": "none"},
    {"tile_id": 4270, "name": "Empty 8", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4271, "name": "Empty 9", "planets": [], "anomaly": "none", "wormhole": "none"},
    {"tile_id": 4272, "name": "Nebula Beta Wormhole", "planets": [], "anomaly": "nebula", "wormhole": "beta"},
    {"tile_id": 4273, "name": "Asteroid Nebula", "planets": [], "anomaly": "asteroid-nebula", "wormhole": "none"},
    {"tile_id": 4274, "name": "Asteroid Gravity Rift", "planets": [], "anomaly": "asteroid-rift", "wormhole": "none"},
    {"tile_id": 4275, "name": "Gravity Rift Gamma Wormhole", "planets": [], "anomaly": "gravity rift", "wormhole": "gamma"},
    {"tile_id": 4276, "name": "Supernova 3 System", "planets": [], "anomaly": "supernova", "wormhole": "none"}
]
