from django.db import migrations


def load_initial_data(apps, schema_editor):
    Planet = apps.get_model("core", "Planet")
    System = apps.get_model("core", "System")
    Faction = apps.get_model("core", "Faction")

    planets = [
        # Home Planets
        {"name": "Jord", "resources": 4, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Moll Primus", "resources": 4, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Darien", "resources": 4, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Muaat", "resources": 4, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Nestphar", "resources": 3, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "[0.0.0]", "resources": 5, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Winnu", "resources": 3, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Mordai II", "resources": 4, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Maaluuk", "resources": 0, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Druaa", "resources": 3, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Arc Prime", "resources": 4, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Wren Terra", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Lisis II", "resources": 1, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Ragh", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Jol", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Nar", "resources": 2, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Tren'lak", "resources": 1, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Quinarra", "resources": 3, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Archon Ren", "resources": 2, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Archon Tau", "resources": 1, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Retillion", "resources": 2, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Shalloq", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Arretze", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Hercant", "resources": 1, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Kamdorn", "resources": 0, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Creuss", "resources": 4, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Ixth", "resources": 3, "influence": 5, "trait": "none", "tech_specialty": "none"},
        {"name": "Arcturus", "resources": 4, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Acheron", "resources": 4, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Elysium", "resources": 4, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "The Dark", "resources": 3, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Naazir", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Rokha", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Valk", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Avar", "resources": 1, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Ylir", "resources": 0, "influence": 2, "trait": "none", "tech_specialty": "none"},
        # Non-Home Planets
        {"name": "Mecatol Rex", "resources": 1, "influence": 6, "trait": "none", "tech_specialty": "none"},
        {"name": "Wellon", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "yellow"},
        {"name": "Vefut II", "resources": 2, "influence": 2, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Thibah", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "blue"},
        {"name": "Tar'mann", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "green"},
        {"name": "Saudor", "resources": 2, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Mehar Xull", "resources": 1, "influence": 3, "trait": "hazardous", "tech_specialty": "red"},
        {"name": "Quann", "resources": 2, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Lodor", "resources": 3, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "New Albion", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "green"},
        {"name": "Starpoint", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Tequ'ran", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Torkan", "resources": 0, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Qucen'n", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Rarron", "resources": 0, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Mellon", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Zohbat", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Lazar", "resources": 1, "influence": 0, "trait": "industrial", "tech_specialty": "yellow"},
        {"name": "Sakulag", "resources": 2, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Dal Bootha", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Xxehan", "resources": 1, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Corneeq", "resources": 1, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Resulon", "resources": 2, "influence": 0, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Centauri", "resources": 1, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Gral", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "blue"},
        {"name": "Bereg", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Lirta IV", "resources": 2, "influence": 3, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Arnor", "resources": 2, "influence": 1, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Lor", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Arinam", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Meer", "resources": 0, "influence": 4, "trait": "hazardous", "tech_specialty": "red"},
        {"name": "Abyz", "resources": 3, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Fria", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Archon Vail", "resources": 1, "influence": 3, "trait": "hazardous", "tech_specialty": "blue"},
        {"name": "Perimeter", "resources": 2, "influence": 1, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Ang", "resources": 2, "influence": 0, "trait": "industrial", "tech_specialty": "red"},
        {"name": "Sem-Lore", "resources": 3, "influence": 2, "trait": "cultural", "tech_specialty": "yellow"},
        {"name": "Vorhal", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "green"},
        {"name": "Atlas", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Cormund", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Everra", "resources": 3, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Accoen", "resources": 2, "influence": 3, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Jeol Ir", "resources": 2, "influence": 3, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Kraag", "resources": 2, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Siig", "resources": 0, "influence": 2, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Ba'Kal", "resources": 3, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Alio Prima", "resources": 1, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Lisis", "resources": 2, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Velnor", "resources": 2, "influence": 1, "trait": "industrial", "tech_specialty": "red"},
        {"name": "Cealdri", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "yellow"},
        {"name": "Xanhact", "resources": 0, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Vega Major", "resources": 2, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Vega Minor", "resources": 1, "influence": 2, "trait": "cultural", "tech_specialty": "blue"},
        {"name": "Loki", "resources": 1, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Abaddon", "resources": 1, "influence": 0, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Ashtroth", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Rigel I", "resources": 0, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Rigel II", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Rigel III", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "green"},
        # Legendaries
        {"name": "Primor", "resources": 2, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Hope's End", "resources": 3, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Mallice", "resources": 0, "influence": 3, "trait": "cultural", "tech_specialty": "none"}
    ]
    planet_objects = {p["name"]: Planet.objects.create(**p) for p in planets}

    systems = [
        {"id": 1, "name": "Sol System", "planets": ["Jord"], "anomaly": "none", "wormhole": "none"},
        {"id": 2, "name": "Mentak System", "planets": ["Moll Primus"], "anomaly": "none", "wormhole": "none"},
        {"id": 3, "name": "Yin System", "planets": ["Darien"], "anomaly": "none", "wormhole": "none"},
        {"id": 4, "name": "Muaat System", "planets": ["Muaat"], "anomaly": "none", "wormhole": "none"},
        {"id": 5, "name": "Arborec System", "planets": ["Nestphar"], "anomaly": "none", "wormhole": "none"},
        {"id": 6, "name": "L1z1x System", "planets": ["[0.0.0]"], "anomaly": "none", "wormhole": "none"},
        {"id": 7, "name": "Winnu System", "planets": ["Winnu"], "anomaly": "none", "wormhole": "none"},
        {"id": 8, "name": "Nekro System", "planets": ["Mordai II"], "anomaly": "none", "wormhole": "none"},
        {"id": 9, "name": "Naalu System", "planets": ["Maaluuk", "Druaa"], "anomaly": "none", "wormhole": "none"},
        {"id": 10, "name": "Letnev System", "planets": ["Arc Prime", "Wren Terra"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 11, "name": "Saar System", "planets": ["Lisis II", "Ragh"], "anomaly": "none", "wormhole": "none"},
        {"id": 12, "name": "Jol-Nar System", "planets": ["Jol", "Nar"], "anomaly": "none", "wormhole": "none"},
        {"id": 13, "name": "Sardakk System", "planets": ["Tren'lak", "Quinarra"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 14, "name": "Xxcha System", "planets": ["Archon Ren", "Archon Tau"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 15, "name": "Yssaril System", "planets": ["Retillion", "Shalloq"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 16, "name": "Hacan System", "planets": ["Arretze", "Hercant", "Kamdorn"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 17, "name": "Creuss Wormhole System", "planets": [], "anomaly": "none", "wormhole": "delta"},
        {"id": 18, "name": "Mecatol Rex System", "planets": ["Mecatol Rex"], "anomaly": "none", "wormhole": "none"},
        {"id": 19, "name": "Wellon System", "planets": ["Wellon"], "anomaly": "none", "wormhole": "none"},
        {"id": 20, "name": "Vefut System", "planets": ["Vefut II"], "anomaly": "none", "wormhole": "none"},
        {"id": 21, "name": "Thibah System", "planets": ["Thibah"], "anomaly": "none", "wormhole": "none"},
        {"id": 22, "name": "Tar'mann System", "planets": ["Tar'mann"], "anomaly": "none", "wormhole": "none"},
        {"id": 23, "name": "Saudor System", "planets": ["Saudor"], "anomaly": "none", "wormhole": "none"},
        {"id": 24, "name": "Mehar Xull System", "planets": ["Mehar Xull"], "anomaly": "none", "wormhole": "none"},
        {"id": 25, "name": "Quann System", "planets": ["Quann"], "anomaly": "none", "wormhole": "beta"},
        {"id": 26, "name": "Lodor System", "planets": ["Lodor"], "anomaly": "none", "wormhole": "alpha"},
        {"id": 27, "name": "New Albion-Starpoint System", "planets": ["New Albion", "Starpoint"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 28, "name": "Tequ'ran-Torkan System", "planets": ["Tequ'ran", "Torkan"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 29, "name": "Qucen'n-Rarron System", "planets": ["Qucen'n", "Rarron"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 30, "name": "Mellon-Zohbat System", "planets": ["Mellon", "Zohbat"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 31, "name": "Lazar-Sakulag System", "planets": ["Lazar", "Sakulag"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 32, "name": "Dal Bootha-Xxehan System", "planets": ["Dal Bootha", "Xxehan"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 33, "name": "Corneeq-Resulon System", "planets": ["Corneeq", "Resulon"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 34, "name": "Centauri-Gral System", "planets": ["Centauri", "Gral"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 35, "name": "Bereg-Lirta System", "planets": ["Bereg", "Lirta IV"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 36, "name": "Arnor-Lor System", "planets": ["Arnor", "Lor"], "anomaly": "none", "wormhole": "none"},
        {"id": 37, "name": "Arinam-Meer System", "planets": ["Arinam", "Meer"], "anomaly": "none", "wormhole": "none"},
        {"id": 38, "name": "Abyz-Fria System", "planets": ["Abyz", "Fria"], "anomaly": "none", "wormhole": "none"},
        {"id": 39, "name": "Alpha Wormhole System", "planets": [], "anomaly": "none", "wormhole": "alpha"},
        {"id": 40, "name": "Beta Wormhole System", "planets": [], "anomaly": "none", "wormhole": "beta"},
        {"id": 41, "name": "Gravity Rift 1 System", "planets": [], "anomaly": "gravity-rift", "wormhole": "none"},
        {"id": 42, "name": "Nebula System", "planets": [], "anomaly": "nebula", "wormhole": "none"},
        {"id": 43, "name": "Supernova 1 System", "planets": [], "anomaly": "supernova", "wormhole": "none"},
        {"id": 44, "name": "Asteroid Field 1 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "none"},
        {"id": 45, "name": "Asteroid Field 2 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "none"},
        {"id": 46, "name": "Empty 1", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 47, "name": "Empty 2", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 48, "name": "Empty 3", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 49, "name": "Empty 4", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 50, "name": "Empty 5", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 51, "name": "Creuss Home System", "planets": ["Creuss"], "anomaly": "none", "wormhole": "delta"},
        {"id": 52, "name": "Mahact System", "planets": ["Ixth"], "anomaly": "none", "wormhole": "none"},
        {"id": 53, "name": "Nomad System", "planets": ["Arcturus"], "anomaly": "none", "wormhole": "none"},
        {"id": 54, "name": "Vuil'raith System", "planets": ["Acheron"], "anomaly": "none", "wormhole": "none"},
        {"id": 55, "name": "Titans System", "planets": ["Elysium"], "anomaly": "none", "wormhole": "none"},
        {"id": 56, "name": "Empyrean System", "planets": ["The Dark"], "anomaly": "none", "wormhole": "none"},
        {"id": 57, "name": "Naaz-Rokha System", "planets": ["Naazir", "Rokha"], "anomaly": "none", "wormhole": "none"},
        {"id": 58, "name": "Argent System", "planets": ["Valk", "Avar", "Ylir"], "anomaly": "none", "wormhole": "none"},
        {"id": 59, "name": "Archon Vail System", "planets": ["Archon Vail"], "anomaly": "none", "wormhole": "none"},
        {"id": 60, "name": "Perimeter System", "planets": ["Perimeter"], "anomaly": "none", "wormhole": "none"},
        {"id": 61, "name": "Ang System", "planets": ["Ang"], "anomaly": "none", "wormhole": "none"},
        {"id": 62, "name": "Sem-Lore System", "planets": ["Sem-Lore"], "anomaly": "none", "wormhole": "none"},
        {"id": 63, "name": "Vorhal System", "planets": ["Vorhal"], "anomaly": "none", "wormhole": "none"},
        {"id": 64, "name": "Atlas System", "planets": ["Atlas"], "anomaly": "none", "wormhole": "beta"},
        {"id": 65, "name": "Primor System", "planets": ["Primor"], "anomaly": "none", "wormhole": "none"},
        {"id": 66, "name": "Hope's End System", "planets": ["Hope's End"], "anomaly": "none", "wormhole": "none"},
        {"id": 67, "name": "Cormund System", "planets": ["Cormund"], "anomaly": "gravity-rift", "wormhole": "none"},
        {"id": 68, "name": "Everra System", "planets": ["Everra"], "anomaly": "nebula", "wormhole": "none"},
        {"id": 69, "name": "Accoen-Jeol System", "planets": ["Accoen", "Jeol Ir"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 70, "name": "Kraag-Siig System", "planets": ["Kraag", "Siig"], "anomaly": "none", "wormhole": "none"},
        {"id": 71, "name": "Ba-Alio System", "planets": ["Ba'Kal", "Alio Prima"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 72, "name": "Lisis-Velnor System", "planets": ["Lisis", "Velnor"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 73, "name": "Cealdri-Xanhact System", "planets": ["Cealdri", "Xanhact"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 74, "name": "Vega System", "planets": ["Vega Major", "Vega Minor"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 75, "name": "Loki-Abaddon-Ashtroth System", "planets": ["Loki", "Abaddon", "Ashtroth"],
         "anomaly": "none", "wormhole": "none"},
        {"id": 76, "name": "Rigel System", "planets": ["Rigel I", "Rigel II", "Rigel III"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 77, "name": "Empty 6", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 78, "name": "Empty 7", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 79, "name": "Asteroid Field 3 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "alpha"},
        {"id": 80, "name": "Supernova 2 System", "planets": [], "anomaly": "supernova", "wormhole": "none"},
        {"id": 81, "name": "Muaat Supernova System", "planets": [], "anomaly": "muaat-supernova", "wormhole": "none"},
        {"id": 82, "name": "Mallice System", "planets": ["Mallice"], "anomaly": "none", "wormhole": "all"}
    ]
    system_objects = {}
    for sys_data in systems:
        system = System.objects.create(name=sys_data["name"], anomaly=sys_data["anomaly"],
                                       wormhole=sys_data["wormhole"])
        for planet_name in sys_data["planets"]:
            system.planets.add(planet_objects[planet_name])
        system_objects[sys_data["name"]] = system

    # Define factions and link to home systems
    factions = [
        {"name": "arborec", "home_system": "Arborec System"},
        {"name": "letnev", "home_system": "Letnev System"},
        {"name": "saar", "home_system": "Saar System"},
        {"name": "muatt", "home_system": "Muaat System"},
        {"name": "hacan", "home_system": "Hacan System"},
        {"name": "sol", "home_system": "Sol System"},
        {"name": "creuss", "home_system": "Creuss Wormhole System"},
        {"name": "l1z1x", "home_system": "L1z1x System"},
        {"name": "mentak", "home_system": "Mentak System"},
        {"name": "naalu", "home_system": "Naalu System"},
        {"name": "sardakk", "home_system": "Sardakk System"},
        {"name": "jolnar", "home_system": "Jol-Nar System"},
        {"name": "winnu", "home_system": "Winnu System"},
        {"name": "xxcha", "home_system": "Xxcha System"},
        {"name": "yin", "home_system": "Yin System"},
        {"name": "yssaril", "home_system": "Yssaril System"},
        {"name": "nekro", "home_system": "Nekro System"},
        {"name": "argent", "home_system": "Argent System"},
        {"name": "empyrean", "home_system": "Empyrean System"},
        {"name": "mahact", "home_system": "Mahact System"},
        {"name": "naazrokha", "home_system": "Naaz-Rokha System"},
        {"name": "nomad", "home_system": "Nomad System"},
        {"name": "ul", "home_system": "Titans System"},
        {"name": "vuilraith", "home_system": "Vuil'raith System"}
    ]
    for faction_data in factions:
        Faction.objects.create(
            name=faction_data["name"],
            home_system=system_objects[faction_data["home_system"]]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
