from django.db import migrations


def load_initial_data(apps, schema_editor):
    Planet = apps.get_model("core", "Planet")
    System = apps.get_model("core", "System")
    Faction = apps.get_model("core", "Faction")

    planets = [
        # Home Planets
        {"name": "Jord", "resources": 4, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Moll Primus", "resources": 4, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Darien", "resources": 4, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Muaat", "resources": 4, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Nestphar", "resources": 3, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "[0.0.0]", "resources": 5, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Winnu", "resources": 3, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Mordai II", "resources": 4, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Maaluuk", "resources": 0, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Druaa", "resources": 3, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Arc Prime", "resources": 4, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Wren Terra", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Lisis II", "resources": 1, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Ragh", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Jol", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Nar", "resources": 2, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Tren'lak", "resources": 1, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Quinarra", "resources": 3, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Archon Ren", "resources": 2, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Archon Tau", "resources": 1, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Retillion", "resources": 2, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Shalloq", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Arretze", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Hercant", "resources": 1, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Kamdorn", "resources": 0, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Creuss", "resources": 4, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Ixth", "resources": 3, "influence": 5, "trait": "none", "tech_specialty": "none"},
        {"name": "Arcturus", "resources": 4, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Acheron", "resources": 4, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Elysium", "resources": 4, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "The Dark", "resources": 3, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Naazir", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Rokha", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Valk", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Avar", "resources": 1, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Ylir", "resources": 0, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Rhune", "resources": 3, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Idyn", "resources": 1, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Kroll", "resources": 1, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Cyrra", "resources": 0, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Kyr", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Pax", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Vess", "resources": 0, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Bohl-Dhur", "resources": 3, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Drah", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Trykk", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Vadarian", "resources": 3, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Norvus", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Blaheo", "resources": 3, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Empero", "resources": 0, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Chrion", "resources": 2, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Demis", "resources": 2, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Axis", "resources": 5, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Sanctuary", "resources": 3, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Shi-Halaum", "resources": 4, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Discordia", "resources": 4, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Cymiae", "resources": 3, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Prind", "resources": 3, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Zelian", "resources": 3, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Gen", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Vaylar", "resources": 3, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Delmor", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Kyd", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Abyssus", "resources": 4, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Louk", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Auldane", "resources": 1, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Ellas", "resources": 3, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Aldra", "resources": 2, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Beata", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Ogdun", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Brthkul", "resources": 1, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Susuros", "resources": 4, "influence": 4, "trait": "none", "tech_specialty": "none"},
        {"name": "Poh", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Orad", "resources": 3, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Benc", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Hau", "resources": 1, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Zarr", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Nokk", "resources": 1, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Last Stop", "resources": 3, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Aysis' Rest", "resources": 4, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Solitude", "resources": 0, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Avicenna", "resources": 4, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Alesna", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Azle", "resources": 2, "influence": 0, "trait": "none", "tech_specialty": "none"},
        {"name": "Gghurn Theta", "resources": 2, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Arche", "resources": 2, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Edyn", "resources": 3, "influence": 3, "trait": "none", "tech_specialty": "none"},
        {"name": "Ekko", "resources": 0, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Okke", "resources": 0, "influence": 1, "trait": "none", "tech_specialty": "none"},
        {"name": "Kjalengard", "resources": 3, "influence": 2, "trait": "none", "tech_specialty": "none"},
        {"name": "Hulgade", "resources": 1, "influence": 0, "trait": "none", "tech_specialty": "none"},
        # Non-Home Planets
        {"name": "Mecatol Rex", "resources": 1, "influence": 6, "trait": "none", "tech_specialty": "none"},
        {"name": "Wellon", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "yellow"},
        {"name": "Vefut II", "resources": 2, "influence": 2, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Thibah", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "blue"},
        {"name": "Tar'mann", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "green"},
        {"name": "Saudor", "resources": 2, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Mehar Xull", "resources": 1, "influence": 3, "trait": "hazardous", "tech_specialty": "red"},
        {"name": "Quann", "resources": 2, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Lodor", "resources": 3, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "New Albion", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "green"},
        {"name": "Starpoint", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Tequ'ran", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Torkan", "resources": 0, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Qucen'n", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Rarron", "resources": 0, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Mellon", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Zohbat", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Lazar", "resources": 1, "influence": 0, "trait": "industrial", "tech_specialty": "yellow"},
        {"name": "Sakulag", "resources": 2, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Dal Bootha", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Xxehan", "resources": 1, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Corneeq", "resources": 1, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Resulon", "resources": 2, "influence": 0, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Centauri", "resources": 1, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Gral", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "blue"},
        {"name": "Bereg", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Lirta IV", "resources": 2, "influence": 3, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Arnor", "resources": 2, "influence": 1, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Lor", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Arinam", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Meer", "resources": 0, "influence": 4, "trait": "hazardous", "tech_specialty": "red"},
        {"name": "Abyz", "resources": 3, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Fria", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Archon Vail", "resources": 1, "influence": 3, "trait": "hazardous", "tech_specialty": "blue"},
        {"name": "Perimeter", "resources": 2, "influence": 1, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Ang", "resources": 2, "influence": 0, "trait": "industrial", "tech_specialty": "red"},
        {"name": "Sem-Lore", "resources": 3, "influence": 2, "trait": "cultural", "tech_specialty": "yellow"},
        {"name": "Vorhal", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "green"},
        {"name": "Atlas", "resources": 3, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Cormund", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Everra", "resources": 3, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Accoen", "resources": 2, "influence": 3, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Jeol Ir", "resources": 2, "influence": 3, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Kraag", "resources": 2, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Siig", "resources": 0, "influence": 2, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Ba'Kal", "resources": 3, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Alio Prima", "resources": 1, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Lisis", "resources": 2, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Velnor", "resources": 2, "influence": 1, "trait": "industrial", "tech_specialty": "red"},
        {"name": "Cealdri", "resources": 0, "influence": 2, "trait": "cultural", "tech_specialty": "yellow"},
        {"name": "Xanhact", "resources": 0, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Vega Major", "resources": 2, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Vega Minor", "resources": 1, "influence": 2, "trait": "cultural", "tech_specialty": "blue"},
        {"name": "Loki", "resources": 1, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Abaddon", "resources": 1, "influence": 0, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Ashtroth", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Rigel I", "resources": 0, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Rigel II", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Rigel III", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "green"},
        {"name": "Troac", "resources": 0, "influence": 4, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Etir V", "resources": 4, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Vioss", "resources": 3, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Fakrenn", "resources": 2, "influence": 2, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "San-Vit", "resources": 3, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Lodran", "resources": 0, "influence": 2, "trait": "hazardous", "tech_specialty": "yellow"},
        {"name": "Dorvok", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "red"},
        {"name": "Derbrae", "resources": 2, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Rysaa", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "blue"},
        {"name": "Moln", "resources": 2, "influence": 0, "trait": "hazardous", "tech_specialty": "green"},
        {"name": "Salin", "resources": 1, "influence": 2, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Gwiyun", "resources": 2, "influence": 2, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Inan", "resources": 1, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Swog", "resources": 1, "influence": 0, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Detic", "resources": 3, "influence": 2, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Lliot", "resources": 0, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Qaak", "resources": 1, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Larred", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Nairb", "resources": 1, "influence": 1, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Mandle", "resources": 1, "influence": 1, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Sierpen", "resources": 2, "influence": 0, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Regnem", "resources": 0, "influence": 2, "trait": "hazardous", "tech_specialty": "none"},
        # Legendaries
        {"name": "Primor", "resources": 2, "influence": 1, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Hope's End", "resources": 3, "influence": 0, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Mallice", "resources": 0, "influence": 3, "trait": "cultural", "tech_specialty": "none"},
        {"name": "Silence", "resources": 2, "influence": 2, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Echo", "resources": 1, "influence": 2, "trait": "hazardous", "tech_specialty": "none"},
        {"name": "Tarrock", "resources": 3, "influence": 0, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Prism", "resources": 0, "influence": 3, "trait": "industrial", "tech_specialty": "none"},
        {"name": "Domna", "resources": 2, "influence": 1, "trait": "hazardous", "tech_specialty": "none"}
    ]
    planet_objects = {p["name"]: Planet.objects.create(**p) for p in planets}

    systems = [
        {"id": 1, "name": "Sol System", "planets": ["Jord"], "anomaly": "none", "wormhole": "none"},
        {"id": 2, "name": "Mentak System", "planets": ["Moll Primus"], "anomaly": "none", "wormhole": "none"},
        {"id": 3, "name": "Yin System", "planets": ["Darien"], "anomaly": "none", "wormhole": "none"},
        {"id": 4, "name": "Muaat System", "planets": ["Muaat"], "anomaly": "none", "wormhole": "none"},
        {"id": 5, "name": "Arborec System", "planets": ["Nestphar"], "anomaly": "none", "wormhole": "none"},
        {"id": 6, "name": "L1z1x System", "planets": ["[0.0.0]"], "anomaly": "none", "wormhole": "none"},
        {"id": 7, "name": "Winnu System", "planets": ["Winnu"], "anomaly": "none", "wormhole": "none"},
        {"id": 8, "name": "Nekro System", "planets": ["Mordai II"], "anomaly": "none", "wormhole": "none"},
        {"id": 9, "name": "Naalu System", "planets": ["Maaluuk", "Druaa"], "anomaly": "none", "wormhole": "none"},
        {"id": 10, "name": "Letnev System", "planets": ["Arc Prime", "Wren Terra"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 11, "name": "Saar System", "planets": ["Lisis II", "Ragh"], "anomaly": "none", "wormhole": "none"},
        {"id": 12, "name": "Jol-Nar System", "planets": ["Jol", "Nar"], "anomaly": "none", "wormhole": "none"},
        {"id": 13, "name": "Sardakk System", "planets": ["Tren'lak", "Quinarra"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 14, "name": "Xxcha System", "planets": ["Archon Ren", "Archon Tau"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 15, "name": "Yssaril System", "planets": ["Retillion", "Shalloq"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 16, "name": "Hacan System", "planets": ["Arretze", "Hercant", "Kamdorn"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 17, "name": "Creuss Wormhole System", "planets": [], "anomaly": "none", "wormhole": "delta"},
        {"id": 18, "name": "Mecatol Rex System", "planets": ["Mecatol Rex"], "anomaly": "none", "wormhole": "none"},
        {"id": 19, "name": "Wellon System", "planets": ["Wellon"], "anomaly": "none", "wormhole": "none"},
        {"id": 20, "name": "Vefut System", "planets": ["Vefut II"], "anomaly": "none", "wormhole": "none"},
        {"id": 21, "name": "Thibah System", "planets": ["Thibah"], "anomaly": "none", "wormhole": "none"},
        {"id": 22, "name": "Tar'mann System", "planets": ["Tar'mann"], "anomaly": "none", "wormhole": "none"},
        {"id": 23, "name": "Saudor System", "planets": ["Saudor"], "anomaly": "none", "wormhole": "none"},
        {"id": 24, "name": "Mehar Xull System", "planets": ["Mehar Xull"], "anomaly": "none", "wormhole": "none"},
        {"id": 25, "name": "Quann System", "planets": ["Quann"], "anomaly": "none", "wormhole": "beta"},
        {"id": 26, "name": "Lodor System", "planets": ["Lodor"], "anomaly": "none", "wormhole": "alpha"},
        {"id": 27, "name": "New Albion-Starpoint System", "planets": ["New Albion", "Starpoint"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 28, "name": "Tequ'ran-Torkan System", "planets": ["Tequ'ran", "Torkan"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 29, "name": "Qucen'n-Rarron System", "planets": ["Qucen'n", "Rarron"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 30, "name": "Mellon-Zohbat System", "planets": ["Mellon", "Zohbat"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 31, "name": "Lazar-Sakulag System", "planets": ["Lazar", "Sakulag"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 32, "name": "Dal Bootha-Xxehan System", "planets": ["Dal Bootha", "Xxehan"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 33, "name": "Corneeq-Resulon System", "planets": ["Corneeq", "Resulon"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 34, "name": "Centauri-Gral System", "planets": ["Centauri", "Gral"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 35, "name": "Bereg-Lirta System", "planets": ["Bereg", "Lirta IV"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 36, "name": "Arnor-Lor System", "planets": ["Arnor", "Lor"], "anomaly": "none", "wormhole": "none"},
        {"id": 37, "name": "Arinam-Meer System", "planets": ["Arinam", "Meer"], "anomaly": "none", "wormhole": "none"},
        {"id": 38, "name": "Abyz-Fria System", "planets": ["Abyz", "Fria"], "anomaly": "none", "wormhole": "none"},
        {"id": 39, "name": "Alpha Wormhole System", "planets": [], "anomaly": "none", "wormhole": "alpha"},
        {"id": 40, "name": "Beta Wormhole System", "planets": [], "anomaly": "none", "wormhole": "beta"},
        {"id": 41, "name": "Gravity Rift 1 System", "planets": [], "anomaly": "gravity-rift", "wormhole": "none"},
        {"id": 42, "name": "Nebula System", "planets": [], "anomaly": "nebula", "wormhole": "none"},
        {"id": 43, "name": "Supernova 1 System", "planets": [], "anomaly": "supernova", "wormhole": "none"},
        {"id": 44, "name": "Asteroid Field 1 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "none"},
        {"id": 45, "name": "Asteroid Field 2 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "none"},
        {"id": 46, "name": "Empty 1", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 47, "name": "Empty 2", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 48, "name": "Empty 3", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 49, "name": "Empty 4", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 50, "name": "Empty 5", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 51, "name": "Creuss Home System", "planets": ["Creuss"], "anomaly": "none", "wormhole": "delta"},
        {"id": 52, "name": "Mahact System", "planets": ["Ixth"], "anomaly": "none", "wormhole": "none"},
        {"id": 53, "name": "Nomad System", "planets": ["Arcturus"], "anomaly": "none", "wormhole": "none"},
        {"id": 54, "name": "Vuil'raith System", "planets": ["Acheron"], "anomaly": "none", "wormhole": "none"},
        {"id": 55, "name": "Titans System", "planets": ["Elysium"], "anomaly": "none", "wormhole": "none"},
        {"id": 56, "name": "Empyrean System", "planets": ["The Dark"], "anomaly": "none", "wormhole": "none"},
        {"id": 57, "name": "Naaz-Rokha System", "planets": ["Naazir", "Rokha"], "anomaly": "none", "wormhole": "none"},
        {"id": 58, "name": "Argent System", "planets": ["Valk", "Avar", "Ylir"], "anomaly": "none", "wormhole": "none"},
        {"id": 59, "name": "Archon Vail System", "planets": ["Archon Vail"], "anomaly": "none", "wormhole": "none"},
        {"id": 60, "name": "Perimeter System", "planets": ["Perimeter"], "anomaly": "none", "wormhole": "none"},
        {"id": 61, "name": "Ang System", "planets": ["Ang"], "anomaly": "none", "wormhole": "none"},
        {"id": 62, "name": "Sem-Lore System", "planets": ["Sem-Lore"], "anomaly": "none", "wormhole": "none"},
        {"id": 63, "name": "Vorhal System", "planets": ["Vorhal"], "anomaly": "none", "wormhole": "none"},
        {"id": 64, "name": "Atlas System", "planets": ["Atlas"], "anomaly": "none", "wormhole": "beta"},
        {"id": 65, "name": "Primor System", "planets": ["Primor"], "anomaly": "none", "wormhole": "none"},
        {"id": 66, "name": "Hope's End System", "planets": ["Hope's End"], "anomaly": "none", "wormhole": "none"},
        {"id": 67, "name": "Cormund System", "planets": ["Cormund"], "anomaly": "gravity-rift", "wormhole": "none"},
        {"id": 68, "name": "Everra System", "planets": ["Everra"], "anomaly": "nebula", "wormhole": "none"},
        {"id": 69, "name": "Accoen-Jeol System", "planets": ["Accoen", "Jeol Ir"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 70, "name": "Kraag-Siig System", "planets": ["Kraag", "Siig"], "anomaly": "none", "wormhole": "none"},
        {"id": 71, "name": "Ba-Alio System", "planets": ["Ba'Kal", "Alio Prima"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 72, "name": "Lisis-Velnor System", "planets": ["Lisis", "Velnor"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 73, "name": "Cealdri-Xanhact System", "planets": ["Cealdri", "Xanhact"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 74, "name": "Vega System", "planets": ["Vega Major", "Vega Minor"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 75, "name": "Loki-Abaddon-Ashtroth System", "planets": ["Loki", "Abaddon", "Ashtroth"],
         "anomaly": "none", "wormhole": "none"},
        {"id": 76, "name": "Rigel System", "planets": ["Rigel I", "Rigel II", "Rigel III"], "anomaly": "none",
         "wormhole": "none"},
        {"id": 77, "name": "Empty 6", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 78, "name": "Empty 7", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 79, "name": "Asteroid Field 3 System", "planets": [], "anomaly": "asteroid-field", "wormhole": "alpha"},
        {"id": 80, "name": "Supernova 2 System", "planets": [], "anomaly": "supernova", "wormhole": "none"},
        {"id": 81, "name": "Muaat Supernova System", "planets": [], "anomaly": "muaat-supernova", "wormhole": "none"},
        {"id": 82, "name": "Mallice System", "planets": ["Mallice"], "anomaly": "none", "wormhole": "all"},
        {"id": 4200, "name": "Veldyr System", "planets": ["Rhune"], "anomaly": "none", "wormhole": "none"},
        {"id": 4222, "name": "Free System", "planets": ["Idyn, Kroll, Cyrra"], "anomaly": "none", "wormhole": "none"},
        {"id": 4223, "name": "Li-Zho System", "planets": ["Kyr, Pax, Vess"], "anomaly": "none", "wormhole": "none"},
        {"id": 4201, "name": "Khrask System", "planets": ["Bohl-Dhur"], "anomaly": "none", "wormhole": "none"},
        {"id": 4212, "name": "Ghemina System", "planets": ["Drah, Trykk"], "anomaly": "none", "wormhole": "none"},
        {"id": 4213, "name": "Vaden System", "planets": ["Vadarian, Norvus"], "anomaly": "none", "wormhole": "none"},
        {"id": 4214, "name": "Mortheus System", "planets": ["Blaheo, Empero"], "anomaly": "nebula", "wormhole": "none"},
        {"id": 4215, "name": "Ilyxum System", "planets": ["Chrion, Demis"], "anomaly": "none", "wormhole": "none"},
        {"id": 4204, "name": "Axis System", "planets": ["Axis"], "anomaly": "none", "wormhole": "none"},
        {"id": 4205, "name": "Olradin System", "planets": ["Sanctuary"], "anomaly": "none", "wormhole": "none"},
        {"id": 4206, "name": "Myko System", "planets": ["Shi-Halaum"], "anomaly": "none", "wormhole": "none"},
        {"id": 4207, "name": "Tnelis System", "planets": ["Discordia"], "anomaly": "none", "wormhole": "none"},
        {"id": 4203, "name": "Cymiae System", "planets": ["Cymiae"], "anomaly": "none", "wormhole": "none"},
        {"id": 4208, "name": "Roh'Dhna System", "planets": ["Prind"], "anomaly": "none", "wormhole": "none"},
        {"id": 4216, "name": "Zelian System", "planets": ["Zelian, Gen"], "anomaly": "asteroid-field", "wormhole": "none"},
        {"id": 4209, "name": "Vaylerian System", "planets": ["Vaylar"], "anomaly": "none", "wormhole": "none"},
        {"id": 4217, "name": "Florzen System", "planets": ["Delmor, Kyd"], "anomaly": "none", "wormhole": "none"},
        {"id": 4210, "name": "Dih-Mohn System", "planets": ["Abyssus"], "anomaly": "none", "wormhole": "none"},
        {"id": 4218, "name": "Celdauri System", "planets": ["Louk, Auldane"], "anomaly": "none", "wormhole": "none"},
        {"id": 4211, "name": "Nivyn System", "planets": ["Ellas"], "anomaly": "gravity-rift", "wormhole": "none"},
        {"id": 4219, "name": "Mirveda System", "planets": ["Aldra, Beata"], "anomaly": "none", "wormhole": "none"},
        {"id": 4220, "name": "Kortali System", "planets": ["Ogdun, Brthkul"], "anomaly": "none", "wormhole": "none"},
        {"id": 4202, "name": "Kollecc System", "planets": ["Susuros"], "anomaly": "none", "wormhole": "none"},
        {"id": 4221, "name": "Rhodun System", "planets": ["Poh, Orad"], "anomaly": "none", "wormhole": "none"},
        {"id": 4224, "name": "Zelian Asteroid Field System", "planets": [], "anomaly": "zelian-asteroid-field", "wormhole": "none"},
        {"id": 4225, "name": "Myko Cataclysm System", "planets": [], "anomaly": "myko-cataclysm", "wormhole": "none"},
        {"id": 4230, "name": "Bentor System", "planets": ["Benc, Hau"], "anomaly": "none", "wormhole": "none"},
        {"id": 4231, "name": "Nokar System", "planets": ["Zarr, Nokk"], "anomaly": "none", "wormhole": "none"},
        {"id": 4228, "name": "Gledge System", "planets": ["Last Stop"], "anomaly": "none", "wormhole": "none"},
        {"id": 4232, "name": "Lanefir System", "planets": ["Aysis' Rest, Solitude"], "anomaly": "none", "wormhole": "none"},
        {"id": 4229, "name": "Kyro System", "planets": ["Avicenna"], "anomaly": "none", "wormhole": "none"},
        {"id": 4227, "name": "Ghoti System", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 4233, "name": "Kolume System", "planets": ["Alesna, Azle"], "anomaly": "none", "wormhole": "none"},
        {"id": 4234, "name": "Cheiran System", "planets": ["Gghurn Theta, Arche"], "anomaly": "none", "wormhole": "none"},
        {"id": 4236, "name": "Edyn System", "planets": ["Edyn, Ekko, Okke"], "anomaly": "none", "wormhole": "none"},
        {"id": 4235, "name": "Kjalengard System", "planets": ["Kjalengard, Hulgade"], "anomaly": "none", "wormhole": "none"},
        {"id": 4253, "name": "Silence System", "planets": ["Silence"], "anomaly": "none", "wormhole": "none"},
        {"id": 4254, "name": "Echo System", "planets": ["Echo"], "anomaly": "none", "wormhole": "none"},
        {"id": 4255, "name": "Tarrock System", "planets": ["Tarrock"], "anomaly": "none", "wormhole": "none"},
        {"id": 4256, "name": "Prism System", "planets": ["Prism"], "anomaly": "none", "wormhole": "none"},
        {"id": 4257, "name": "Troac System", "planets": ["Troac"], "anomaly": "none", "wormhole": "none"},
        {"id": 4258, "name": "Etir System", "planets": ["Etir V"], "anomaly": "none", "wormhole": "none"},
        {"id": 4259, "name": "Vioss System", "planets": ["Vioss"], "anomaly": "none", "wormhole": "none"},
        {"id": 4260, "name": "Fakrenn System", "planets": ["Fakrenn"], "anomaly": "none", "wormhole": "alpha"},
        {"id": 4261, "name": "San-Lodran System", "planets": ["San-Vit, Lodran"], "anomaly": "none", "wormhole": "none"},
        {"id": 4262, "name": "Dorvok-Derbrae System", "planets": ["Dorvok, Derbrae"], "anomaly": "none", "wormhole": "none"},
        {"id": 4263, "name": "Rysaa-Moln System", "planets": ["Rysaa, Moln"], "anomaly": "none", "wormhole": "none"},
        {"id": 4264, "name": "Salin-Gwiyun System", "planets": ["Salin, Gwiyun"], "anomaly": "none", "wormhole": "none"},
        {"id": 4265, "name": "Inan-Swog System", "planets": ["Inan, Swog"], "anomaly": "none", "wormhole": "none"},
        {"id": 4266, "name": "Detic-Lliot System", "planets": ["Detic, Lliot"], "anomaly": "none", "wormhole": "none"},
        {"id": 4267, "name": "Qaak-Larred-Nairb System", "planets": ["Qaak, Larred, Nairb"], "anomaly": "none", "wormhole": "none"},
        {"id": 4268, "name": "Mandle-Sierpen-Regnem System", "planets": ["Mandle, Sierpen, Regnem"], "anomaly": "none", "wormhole": "none"},
        {"id": 4269, "name": "Domna System", "planets": ["Domna"], "anomaly": "nebula", "wormhole": "none"},
        {"id": 4270, "name": "Empty 8", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 4271, "name": "Empty 9", "planets": [], "anomaly": "none", "wormhole": "none"},
        {"id": 4272, "name": "Nebula Beta Wormhole", "planets": [], "anomaly": "nebula", "wormhole": "beta"},
        {"id": 4273, "name": "Asteroid Nebula", "planets": [], "anomaly": "asteroid-nebula", "wormhole": "none"},
        {"id": 4274, "name": "Asteroid Gravity Rift", "planets": [], "anomaly": "asteroid-rift", "wormhole": "none"},
        {"id": 4275, "name": "Gravity Rift Gamma Wormhole", "planets": [], "anomaly": "gravity rift", "wormhole": "gamma"},
        {"id": 4276, "name": "Supernova 3 System", "planets": [], "anomaly": "supernova", "wormhole": "none"}
    ]
    system_objects = {}
    for sys_data in systems:
        system = System.objects.create(name=sys_data["name"], anomaly=sys_data["anomaly"],
                                       wormhole=sys_data["wormhole"])
        for planet_name in sys_data["planets"]:
            system.planets.add(planet_objects[planet_name])
        system_objects[sys_data["name"]] = system

    # Define factions and link to home systems
    factions = [
        {"name": "arborec", "home_system": "Arborec System"},
        {"name": "letnev", "home_system": "Letnev System"},
        {"name": "saar", "home_system": "Saar System"},
        {"name": "muatt", "home_system": "Muaat System"},
        {"name": "hacan", "home_system": "Hacan System"},
        {"name": "sol", "home_system": "Sol System"},
        {"name": "creuss", "home_system": "Creuss Wormhole System"},
        {"name": "l1z1x", "home_system": "L1z1x System"},
        {"name": "mentak", "home_system": "Mentak System"},
        {"name": "naalu", "home_system": "Naalu System"},
        {"name": "sardakk", "home_system": "Sardakk System"},
        {"name": "jolnar", "home_system": "Jol-Nar System"},
        {"name": "winnu", "home_system": "Winnu System"},
        {"name": "xxcha", "home_system": "Xxcha System"},
        {"name": "yin", "home_system": "Yin System"},
        {"name": "yssaril", "home_system": "Yssaril System"},
        {"name": "nekro", "home_system": "Nekro System"},
        {"name": "argent", "home_system": "Argent System"},
        {"name": "empyrean", "home_system": "Empyrean System"},
        {"name": "mahact", "home_system": "Mahact System"},
        {"name": "naazrokha", "home_system": "Naaz-Rokha System"},
        {"name": "nomad", "home_system": "Nomad System"},
        {"name": "ul", "home_system": "Titans System"},
        {"name": "vuilraith", "home_system": "Vuil'raith System"},
        {"name": "ilyxum", "home_system": "Ilyxum System"},
        {"name": "celdauri", "home_system": "Celdauri System"},
        {"name": "dihmohn", "home_system": "Dih-Mohn System"},
        {"name": "florzen", "home_system": "Florzen System"},
        {"name": "free", "home_system": "Free System"},
        {"name": "ghemina", "home_system": "Ghemina System"},
        {"name": "mortheus", "home_system": "Mortheus System"},
        {"name": "kollecc", "home_system": "Kollecc System"},
        {"name": "kortali", "home_system": "Kortali System"},
        {"name": "lizho", "home_system": "Li-Zho System"},
        {"name": "khrask", "home_system": "Khrask System"},
        {"name": "mirveda", "home_system": "Mirveda System"},
        {"name": "myko", "home_system": "Myko System"},
        {"name": "nivyn", "home_system": "Nivyn System"},
        {"name": "olradin", "home_system": "Olradin System"},
        {"name": "rohdina", "home_system": "Roh'Dhna System"},
        {"name": "cymiae", "home_system": "Cymiae System"},
        {"name": "axis", "home_system": "Axis System"},
        {"name": "tnelis", "home_system": "Tnelis System"},
        {"name": "vaden", "home_system": "Vaden System"},
        {"name": "vaylerian", "home_system": "Vaylerian System"},
        {"name": "veldyr", "home_system": "Veldyr System"},
        {"name": "rhodun", "home_system": "Rhodun System"},
        {"name": "zelian", "home_system": "Zelian System"},
        {"name": "bentor", "home_system": "Bentor System"},
        {"name": "kjalengard", "home_system": "Kjalengard System"},
        {"name": "cheiran", "home_system": "Cheiran System"},
        {"name": "edyn", "home_system": "Edyn System"},
        {"name": "ghoti", "home_system": "Ghoti System"},
        {"name": "gledge", "home_system": "Gledge System"},
        {"name": "kyro", "home_system": "Kyro System"},
        {"name": "lanefir", "home_system": "Lanefir System"},
        {"name": "kolume", "home_system": "Kolume System"},
        {"name": "nokar", "home_system": "Nokar System"}
    ]
    for faction_data in factions:
        Faction.objects.create(
            name=faction_data["name"],
            home_system=system_objects[faction_data["home_system"]]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
