"""
Django settings for oracle-rex project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-s6+_jwtlw!br7qrh^lv@o*pxju=ey7!arv6srw0#xs)($8hx(8',
)

# Fernet key used to encrypt BYOK API keys before they enter the Django-Q broker
# table (see core.service.ai.crypto). Set AIJOB_FERNET_KEY in production so the
# web and worker processes share a stable key; otherwise one is derived from
# SECRET_KEY, which both processes already read identically.
AIJOB_FERNET_KEY = os.environ.get('AIJOB_FERNET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
# Default False (production-safe). Set DJANGO_DEBUG=1 for local development so
# runserver serves your edited static/ files directly — otherwise WhiteNoise
# serves the collected staticfiles/ copies and you must re-run collectstatic
# after every JS/CSS change.
DEBUG = os.environ.get('DJANGO_DEBUG', '') == '1'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', "oracle-rex.onrender.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_q',
    'core',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oracle-rex.urls'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# In development (DEBUG), have WhiteNoise serve files straight from the static/
# source dirs via the staticfiles finders and re-check them on each request, so
# edits show up without re-running collectstatic. No effect in production, where
# WhiteNoise serves the collected, hashed staticfiles/ as usual.
if DEBUG:
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "https://oracle-rex.onrender.com",
]

CORS_ALLOW_CREDENTIALS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oracle-rex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# Env-driven via DATABASE_URL (dj-database-url). Production on Render points this
# at Postgres — the same instance the web service and the Django-Q background
# worker share, which is what makes the ORM broker work without Redis. With no
# DATABASE_URL set, it falls back to the local SQLite file so a fresh checkout
# still runs. ``conn_max_age`` keeps Postgres connections warm; the worker holds
# long-lived connections while polling the broker table.

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# When running on SQLite (the default, zero-cost single-process deployment), use
# WAL mode and a busy timeout so the web request thread and the in-process AI job
# threads don't trip over each other on concurrent writes. WAL is enabled per
# connection in core/apps.py; the busy timeout is set here.
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    DATABASES['default'].setdefault('OPTIONS', {})['timeout'] = 20


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging
# Surfaces AI service warnings (e.g. structured-output fallbacks, validation
# failures) and errors to the console so they're debuggable locally and on Render.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django_q': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# --- Async AI jobs (Milestone 2) ------------------------------------------
#
# Execution backend for AI jobs:
#   'thread'   (default) run jobs in an in-process thread pool on the web
#              service — no extra process, runs on a single free host.
#   'django_q' enqueue to the Django-Q ORM broker for a separate, durable
#              worker (`manage.py qcluster`); survives restarts but needs the
#              worker process (paid on Render) and ideally Postgres.
AI_JOB_BACKEND = os.environ.get('AI_JOB_BACKEND', 'thread')
AI_JOB_THREADS = int(os.environ.get('AI_JOB_THREADS', '4'))

# Single time budget for a provider call, shared by the service layer
# (core/service/ai/config.py reads the same AI_REQUEST_TIMEOUT env var) and the
# downstream timeouts below, so they stay coherent: the provider call gets
# AI_REQUEST_TIMEOUT, and the worker kill / stale-job reaper sit above it so the
# graceful in-task timeout normally wins.
AI_REQUEST_TIMEOUT = float(os.environ.get('AI_REQUEST_TIMEOUT', '180'))

# How long (seconds) a job may sit in 'running' before the status endpoint reaps
# it to 'timeout' — the safety net for the in-process thread backend. Above the
# provider timeout so a normally-slow call isn't reaped mid-flight.
AI_JOB_STALE_SECONDS = int(AI_REQUEST_TIMEOUT) + 120

# Django-Q2 config — only used when AI_JOB_BACKEND == 'django_q'.
#
# Uses the ORM broker ('orm': 'default'), so the shared state between the web
# process and the worker is the database itself — no Redis. Run the worker with
# `python manage.py qcluster`. Locally that's a second process alongside
# `runserver` (see the Procfile); on Render it's a dedicated Background Worker
# pointed at the same Postgres instance.
#
# 'timeout' kills a task that runs too long (a hung provider call) so a job can't
# wedge a worker forever; the completion hook then marks the AIJob 'timeout'. It
# sits above the service layer's own provider timeout (AI_REQUEST_TIMEOUT) so the
# graceful in-task timeout normally wins and this is only a hard safety net.
# 'retry' must exceed 'timeout'.
Q_CLUSTER = {
    'name': 'oracle_rex',
    'workers': int(os.environ.get('Q_WORKERS', '2')),
    'timeout': int(AI_REQUEST_TIMEOUT) + 30,
    'retry': int(AI_REQUEST_TIMEOUT) + 90,
    'max_attempts': 1,
    'catch_up': False,
    'save_limit': 250,
    'orm': 'default',
    # In tests / one-off scripts, force synchronous execution so enqueued tasks
    # run inline without a separate qcluster process.
    'sync': os.environ.get('Q_SYNC', '') == '1',
}
